#!/usr/bin/env python
# coding: utf-8

"""
Created on 2020.07.03
Author: MCHsu1
"""

import pymssql
from sinbad import *
from datetime import datetime
from pandas.io.json import json_normalize

# connect to MSSQL
conn = pymssql.connect(server='labdb01', database='WEC_EDW_DEV')  
cursor = conn.cursor()  


# Fetch data from USGS
def usgs():
    ds = Data_Source.connect("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojson")
    ds.set_cache_timeout(180)    # force cache refresh every 3 minutes
    
    ds.load()
    data = ds.fetch(base_path = "features")

    #data = ds.fetch("title", "time", "mag", "time","detail",base_path = "features/properties")
    #data_geometry = ds.fetch("coordinates" ,base_path = "features/geometry")
    #for d in data:
    #    print(d["title"] + "\t[" + ts_to_time(d["time"]) + "] " + str(d["mag"]) )
        
    #ds.print_description()
    return data

def ts_to_time(v):
    return datetime.fromtimestamp(float(v)/1000).strftime("%Y-%m-%d %H:%M:%S")
def ts_to_updated(x): 
    return datetime.fromtimestamp(float(x)/1000).strftime("%Y-%m-%d %H:%M:%S")


# Define DataFrame
DF=usgs()

DF_Feature=json_normalize(DF['features'])
DF_Feature=DF_Feature[['id','properties.time','properties.updated','properties.place',
                       'properties.type','geometry.coordinates','properties.mag','properties.magType']]
 
    
# Excecute SQL and insert into MSSQL    
for i in range (0, DF_Feature.shape[0]):                      
    long1=float(DF_Feature.iloc[i]['geometry.coordinates'][0])
    lat1=float(DF_Feature.iloc[i]['geometry.coordinates'][1])
    eventID=DF_Feature.iloc[i]['id']
    time=DF_Feature.iloc[i]['properties.time']
    updated=DF_Feature.iloc[i]['properties.updated']
    eventType=DF_Feature.iloc[i]['properties.type']   
    place=DF_Feature.iloc[i]['properties.place']
    mag=DF_Feature.iloc[i]['properties.mag']
    magType=DF_Feature.iloc[i]['properties.magType']
    
    cursor.execute('''
INSERT INTO WEC_EDW_DEV.dbo.tblEAS_Event_EQ (id, eventTime, updatedTime, eventType, place, latitude, longitude, magType, mag) 
values (%s,%s,%s,%s,%s,%s,%s,%s,%s) ''', (eventID, ts_to_time(time), ts_to_updated(updated), eventType, place, lat1, long1, magType, mag ) )
    
    conn.commit()
    #print (eventID , ts_to_time(time), ts_to_updated(updated), eventType, place, lat1, long1, magType, mag)


# Successful notification    
print('Insert successfully!')

cursor.close()
conn.close()
